add_executable(get_graph_dot get_graph_dot.cu)
add_executable(cuda_memory_pool cuda_memory_pool.cu)
add_executable(cuda_graph_memory_pool cuda_graph_memory_pool.cu)
add_executable(cuda_graph_cudamalloc cuda_graph_cudamalloc.cu)
add_executable(cuda_graph_memory_pool_free cuda_graph_memory_pool_free.cu)
add_executable(cuda_graph_memory_pool_full cuda_graph_memory_pool_full.cu)
add_executable(cuda_graph_legacy_stream cuda_graph_legacy_stream.cu)

target_link_libraries(get_graph_dot PRIVATE cudart)
target_link_libraries(cuda_memory_pool PRIVATE cudart)
target_link_libraries(cuda_graph_memory_pool PRIVATE cudart)
target_link_libraries(cuda_graph_cudamalloc PRIVATE cudart)
target_link_libraries(cuda_graph_memory_pool_free PRIVATE cudart)
target_link_libraries(cuda_graph_memory_pool_full PRIVATE cudart)
target_link_libraries(cuda_graph_legacy_stream PRIVATE cudart)